name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ls -alt
    - run: npm i
    - run: npm run test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm i
      - uses: ./
        id: package_update
      - run: echo "output has_npm_update ${{ steps.package_update.outputs.has_npm_update }}"
      - run: echo "output has_major_npm_update ${{ steps.package_update.outputs.has_major_npm_update }}"
      # - run: echo "output npm_update_formatted ${{ steps.package_update.outputs.npm_update_formatted }}"
      - run: echo "output npm_update_json ${{ steps.package_update.outputs.npm_update_json }}"
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: author
          text: |
            ```
            has update: ${{ steps.package_update.outputs.has_npm_update }}
            has major update: ${{ steps.package_update.outputs.has_major_npm_update }}

            **New major update available**
            ${{ steps.package_update.outputs.npm_update_formatted }}
            ```
          username: 'アップデートマン'
          mention: 'UF660LNH2'
          if_mention: always
          icon_emoji: ':octocat:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: steps.package_update.outputs.has_major_npm_update == 'true'
