name: "package-update"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  pacage-update:
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H-%M')"
      - uses: actions/checkout@v2
      - name: Npm install
        run: npm i
      - uses: ./
        id: package_update
      - name: Npm update
        run: npm update
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ github.token }}
          title: Update npm packages
          commit-message: Update npm packages
          branch: package-update/${{ steps.current_date.outputs.date }}
          labels: ''
          reviewers: ''
          body: |
            # Package Update

            ```
            ${{ steps.package_update.outputs.npm_update_formatted }}
            ```

            createdAt: ${{ steps.current_date.outputs.date }}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: action
          text: |
            *New major update available*
            ```
            ${{ steps.package_update.outputs.npm_update_formatted_major_update }}
            ```

            *Create Pull Request*
            Pull Request URL: https://github.com/pull/${{ steps.cpr.outputs.pr_number }}
          author_name: ${{ github.actor }}
          username: 'アップデートマン'
          mention: 'UF660LNH2'
          if_mention: always
          icon_emoji: ':octocat:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: steps.package_update.outputs.has_major_npm_update == true
