name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ls -alt
    - run: npm i
    - run: npm run test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Npm install
        run: npm i
      - uses: ./
        id: package_update
      - name: Npm update
        run: npm update
      - name: Create pull request
        id: cpr
        uses: peter-evans/create-pull-request@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'Update npm packages'
          commit-message: 'Update npm packages'
          branch: package-update/${{ github.committed_at }}
          body: |
            # Package Update

            createdAt: ${{ github.committed_at }}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: ''
          text: |
            **New major update available**

            ```
            ${{ steps.package_update.outputs.npm_update_formatted_major_update }}
            ```

            **Create Pull Request**
            Pull Request Number: ${{ steps.cpr.outputs.pr_number }}
          username: 'アップデートマン'
          mention: 'UF660LNH2'
          if_mention: always
          icon_emoji: ':octocat:'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
        # if: steps.package_update.outputs.has_major_npm_update == 'true'
