name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ls -alt
    - run: npm i
    - run: npm run test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: package_update
      - run: echo "output has_npm_update ${{ steps.package_update.outputs.has_npm_update }}"
      - run: echo "output has_major_npm_update ${{ steps.package_update.outputs.has_major_npm_update }}"
      # - run: echo "output npm_update_formatted ${{ steps.package_update.outputs.npm_update_formatted }}"
      - run: echo "output npm_update_json ${{ steps.package_update.outputs.npm_update_json }}"
