name: "units-test"
on:
  pull_request:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  # unit tests
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: ls -alt
    - run: npm i
    - run: npm run test

  # test action works running from the graph
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        id: package_update
        with:
          execute_directories: |
            hoge
            fuga
      - run: echo 'output has_npm_update: ${{ steps.package_update.outputs.has_npm_update }}'
      - run: echo 'output has_major_npm_update: ${{ steps.package_update.outputs.has_major_npm_update }}'
